# CodeRabbit Configuration
version: 1

# Review settings
review:
  # Default review language
  default_language: en-US

  # Configure the review engine based on languages
  engines:
    typescript:
      enabled: true
      # Focus on best practices and patterns for TypeScript/React
      review_comment_settings:
        suggestion_threshold: 2 # Requires stronger confidence for suggestions
      review_criteria:
        best_practices: high
        security: high
        performance: medium
        complexity: medium
        maintainability: high

    solidity:
      enabled: true
      # Focus heavily on security for smart contracts
      review_criteria:
        security: high
        best_practices: high
        gas_optimization: high

    sql:
      enabled: true
      # Focus on database best practices and security
      review_criteria:
        security: high
        performance: high
        readability: medium

# Path-based review configuration
path_filters:
  ignore:
    # Build artifacts and dependencies
    - '**/*.min.js'
    - '**/*.min.css'
    - '**/node_modules/**'
    - '**/dist/**'
    - '**/build/**'
    - '**/.next/**'
    - '**/.cache/**'

    # Generated code
    - '**/generated/**'

    # Lock files
    - 'pnpm-lock.yaml'

    # Test mocks and fixtures
    - '**/__mocks__/**'
    - '**/__fixtures__/**'
    - '**/*test-utils/**'

  # Path-specific review instructions
  paths:
    # Smart Contracts
    'packages/storage-evm/contracts/**':
      review_criteria:
        security: high
        gas_optimization: high
      description: 'Solidity smart contracts - focus on security, gas optimization and best practices'

    # Database
    'packages/storage-postgres/migrations/**':
      review_criteria:
        data_integrity: high
        performance: high
      description: 'Database migrations - focus on backward compatibility and data integrity'

    # Authentication
    'packages/authentication/**':
      review_criteria:
        security: high
        privacy: high
      description: 'Authentication - focus on security and privacy best practices'

    # Cookie management
    'packages/cookie/**':
      review_criteria:
        security: high
        privacy: high
      description: 'Cookie management - focus on security and privacy compliance'

    # Core business logic
    'packages/core/**':
      review_criteria:
        maintainability: high
        testability: high
        performance: medium
      description: 'Core business logic - focus on maintainability and testability'

    # Epics (React state management)
    'packages/epics/**':
      review_criteria:
        maintainability: high
        state_management: high
      description: 'Epics - focus on state management and maintainability'

    # EVM integration
    'packages/evm/**':
      review_criteria:
        security: high
        error_handling: high
      description: 'EVM interactions - focus on security and error handling'

    # Feature flags
    'packages/feature-flags/**':
      review_criteria:
        maintainability: high
      description: 'Feature flags - focus on maintainability and clean implementation'

    # Internationalization
    'packages/i18n/**':
      review_criteria:
        internationalization: high
        accessibility: high
      description: 'Internationalization - focus on i18n best practices and accessibility'

    # Developer tools
    'packages/tools/**':
      review_criteria:
        maintainability: high
        code_quality: medium
      description: 'Developer tools - focus on maintainability and code quality'

    # UI utilities
    'packages/ui-utils/**':
      review_criteria:
        reusability: high
        performance: medium
        accessibility: high
      description: 'UI utilities - focus on reusability, accessibility and maintainability'

    # UI components
    'packages/ui/**':
      review_criteria:
        performance: high
        accessibility: high
        maintainability: high
      description: 'UI components - focus on performance, accessibility, and maintainability'

    # Frontend applications
    'apps/**':
      review_criteria:
        performance: high
        accessibility: medium
        maintainability: high
      description: 'Frontend applications - focus on performance and maintainability'

# PR size settings for manageable reviews
pr_size:
  small: 150
  medium: 500
  large: 1000
  xl: 2000

# Chat settings
chat:
  auto_reply: |
    Thank you for your PR! I'll be assisting with code review.
    This repository contains multiple languages and technologies, so please let me know if you'd like me to focus on specific areas.
