export const categories = [
  { value: 'air', label: 'Air' },
  { value: 'art', label: 'Art' },
  { value: 'education', label: 'Education' },
  { value: 'energy', label: 'Energy' },
  { value: 'fauna', label: 'Fauna' },
  { value: 'flora', label: 'Flora' },
  { value: 'food', label: 'Food' },
  { value: 'fungi', label: 'Fungi' },
  { value: 'health', label: 'Health' },
  { value: 'housing', label: 'Housing' },
  { value: 'mobility', label: 'Mobility' },
  { value: 'sandbox', label: 'Sandbox' },
  { value: 'soil', label: 'Soil' },
  { value: 'tech', label: 'Tech' },
  { value: 'usecase', label: 'Use Case' },
  { value: 'water', label: 'Water' },
];
