import { Category } from './types';

type CategoryOption = {
  value: Category;
  label: string;
  visibleTag: boolean;
  archive: boolean;
  additional: boolean;
};

export const categories: CategoryOption[] = [
  // archive categories for backword compatibility
  {
    value: 'art',
    label: 'Art',
    visibleTag: false,
    archive: true,
    additional: false,
  },
  {
    value: 'events',
    label: 'Events',
    visibleTag: false,
    archive: true,
    additional: false,
  },
  // actual categories
  {
    value: 'arts',
    label: 'Arts',
    visibleTag: true,
    archive: false,
    additional: false,
  },
  {
    value: 'biodiversity',
    label: 'Biodiversity',
    visibleTag: true,
    archive: false,
    additional: false,
  },
  {
    value: 'bioregions',
    label: 'Bioregions',
    visibleTag: true,
    archive: false,
    additional: false,
  },
  {
    value: 'cities',
    label: 'Cities',
    visibleTag: true,
    archive: false,
    additional: false,
  },
  {
    value: 'culture',
    label: 'Culture',
    visibleTag: true,
    archive: false,
    additional: false,
  },
  {
    value: 'education',
    label: 'Education',
    visibleTag: true,
    archive: false,
    additional: false,
  },
  {
    value: 'emergency',
    label: 'Emergency',
    visibleTag: true,
    archive: false,
    additional: false,
  },
  {
    value: 'energy',
    label: 'Energy',
    visibleTag: true,
    archive: false,
    additional: false,
  },
  {
    value: 'finance',
    label: 'Finance',
    visibleTag: true,
    archive: false,
    additional: false,
  },
  {
    value: 'food',
    label: 'Food',
    visibleTag: true,
    archive: false,
    additional: false,
  },
  {
    value: 'gaming',
    label: 'Gaming',
    visibleTag: true,
    archive: false,
    additional: false,
  },
  {
    value: 'governance',
    label: 'Governance',
    visibleTag: true,
    archive: false,
    additional: false,
  },
  {
    value: 'health',
    label: 'Health',
    visibleTag: true,
    archive: false,
    additional: false,
  },
  {
    value: 'housing',
    label: 'Housing',
    visibleTag: true,
    archive: false,
    additional: false,
  },
  {
    value: 'innovation',
    label: 'Innovation',
    visibleTag: true,
    archive: false,
    additional: false,
  },
  {
    value: 'knowledge',
    label: 'Knowledge',
    visibleTag: true,
    archive: false,
    additional: false,
  },
  {
    value: 'land',
    label: 'Land',
    visibleTag: true,
    archive: false,
    additional: false,
  },
  {
    value: 'media',
    label: 'Media',
    visibleTag: true,
    archive: false,
    additional: false,
  },
  {
    value: 'mobility',
    label: 'Mobility',
    visibleTag: true,
    archive: false,
    additional: false,
  },
  {
    value: 'networks',
    label: 'Networks',
    visibleTag: true,
    archive: false,
    additional: false,
  },
  {
    value: 'ocean',
    label: 'Ocean',
    visibleTag: true,
    archive: false,
    additional: false,
  },
  {
    value: 'distribution',
    label: 'Distribution',
    visibleTag: true,
    archive: false,
    additional: false,
  },
  {
    value: 'goods',
    label: 'Goods',
    visibleTag: true,
    archive: false,
    additional: false,
  },
  {
    value: 'services',
    label: 'Services',
    visibleTag: true,
    archive: false,
    additional: false,
  },
  {
    value: 'sport',
    label: 'Sport',
    visibleTag: true,
    archive: false,
    additional: false,
  },
  {
    value: 'tech',
    label: 'Tech',
    visibleTag: true,
    archive: false,
    additional: false,
  },
  {
    value: 'tourism',
    label: 'Tourism',
    visibleTag: true,
    archive: false,
    additional: false,
  },
  {
    value: 'villages',
    label: 'Villages',
    visibleTag: true,
    archive: false,
    additional: false,
  },
  {
    value: 'water',
    label: 'Water',
    visibleTag: true,
    archive: false,
    additional: false,
  },
  {
    value: 'wellbeing',
    label: 'Wellbeing',
    visibleTag: true,
    archive: false,
    additional: false,
  },
  {
    value: 'sandbox',
    label: 'Sandbox',
    visibleTag: true,
    archive: false,
    additional: true,
  },
  {
    value: 'usecase',
    label: 'Use Case',
    visibleTag: true,
    archive: false,
    additional: true,
  },
];
