export const categories = [
  { value: 'art', label: 'Art' },
  { value: 'biodiversity', label: 'Biodiversity' },
  { value: 'education', label: 'Education' },
  { value: 'energy', label: 'Energy' },
  { value: 'events', label: 'Events' },
  { value: 'finance', label: 'Finance' },
  { value: 'governance', label: 'Governance' },
  { value: 'health', label: 'Health' },
  { value: 'housing', label: 'Housing' },
  { value: 'land', label: 'Land' },
  { value: 'mobility', label: 'Mobility' },
  { value: 'ocean', label: 'Ocean' },
  { value: 'sandbox', label: 'Sandbox' },
  { value: 'tech', label: 'Tech' },
  { value: 'usecase', label: 'Use Case' },
];
