name: 'Setup Preview Database'
description: 'Sets up a preview database branch if there are migration changes'

inputs:
  neon-project-id:
    description: 'Neon Project ID'
    required: true
  neon-api-key:
    description: 'Neon API Key'
    required: true
  db-username:
    description: 'Database username'
    required: true
  db-name:
    description: 'Database name'
    required: true
  pr-number:
    description: 'Pull request number'
    required: true

outputs:
  branch_db_url:
    description: 'The database URL to use'
    value: ${{ steps.set-db-url.outputs.db_url }}

runs:
  using: 'composite'
  steps:
    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v8

    - name: Create Neon Branch
      id: create-branch
      uses: neondatabase/create-branch-action@v5
      with:
        project_id: ${{ inputs.neon-project-id }}
        branch_name: preview/pr-${{ inputs.pr-number }}-${{ steps.branch-name.outputs.current_branch }}
        username: ${{ inputs.db-username }}
        database: ${{ inputs.db-name }}
        api_key: ${{ inputs.neon-api-key }}

    - name: Set DB URL
      id: set-db-url
      shell: bash
      run: |
        echo "branch_db_url=${{ steps.create-branch.outputs.db_url_with_pooler }}" >> $GITHUB_OUTPUT
