export const HYPHA_LOCALE = 'HYPHA_LOCALE';
export const HYPHA_AUTH_PROVIDER = 'HYPHA_AUTH_PROVIDER';
export const HYPHA_SHOW_LANGUAGE_SELECT = 'HYPHA_SHOW_LANGUAGE_SELECT';
export const HYPHA_ENABLE_AI_CHAT = 'HYPHA_ENABLE_AI_CHAT';
export const HYPHA_ENABLE_HUMAN_CHAT = 'HYPHA_ENABLE_HUMAN_CHAT';
