export const metadata = {
  title: 'Hypha | Network',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({
  children,
  aside,
}: {
  children: React.ReactNode;
  aside: React.ReactNode;
}) {
  return (
    <>
      <link
        rel="preload"
        href="/geo/land-50m.json"
        as="fetch"
        crossOrigin="anonymous"
      />
      <div className="w-full h-full flex">
        {children}
        {aside}
      </div>
    </>
  );
}
