export const metadata = {
  title: 'Hypha | Network',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({
  children,
  aside,
}: {
  children: React.ReactNode;
  aside: React.ReactNode;
}) {
  // See my-spaces/layout.tsx — aside first + row-reverse for correct stacking vs SidePanel.
  return (
    <div className="flex h-full w-full flex-row-reverse">
      {aside}
      {children}
    </div>
  );
}
