name: CI

on:
  push:
    branches:
      - main
  pull_request: # We need this back for GitHub to register the check
  merge_group:
  workflow_run:
    workflows: ['Deploy Preview']
    types:
      - completed
    branches-ignore:
      - main

permissions:
  actions: read
  contents: read

jobs:
  # Add a new job to handle the initial PR trigger
  check:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Deploy Preview
        run: |
          echo "This check will be skipped, actual checks will run after Deploy Preview completes"
          exit 0

  main:
    # Skip this job on the initial PR trigger
    if: |
      github.event_name == 'push' ||
      github.event_name == 'merge_group' ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-latest
    env:
      DEFAULT_DB_URL: ${{ secrets.POSTGRES_URL }}
      # Use BRANCH_DB_URL from deploy-preview if available, otherwise use DEFAULT_DB_URL
      BRANCH_DB_URL: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.outputs.branch_db_url || secrets.POSTGRES_URL }}

    steps:
      # Debug step to understand the context
      - name: Debug Event
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Workflow conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Branch DB URL available: ${{ github.event.workflow_run.outputs.branch_db_url != '' }}"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      # Connect your workspace on nx.app and uncomment this to enable task distribution.
      # The "--stop-agents-after" is optional, but allows idle agents to shut down once the "e2e-ci" targets have been requested
      # - run: npx nx-cloud start-ci-run --distribute-on="5 linux-medium-js" --stop-agents-after="e2e-ci"

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 18.19.1
          cache: 'pnpm'

      - run: pnpm install
      - uses: nrwl/nx-set-shas@v4

      - run: pnpm run format:check

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: npx nx-cloud record -- echo Hello World
      - run: npx nx affected -t lint test build

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - run: npx nx affected --parallel 1 -t e2e
