name: Deploy Production

concurrency: production

on:
  push:
    branches:
      - 'main'
env:
  NX_VERCEL_REMOTE_CACHE_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  NX_VERCEL_REMOTE_CACHE_TEAM: ${{ secrets.VERCEL_TEAM_ID }}

jobs:
  deploy-production:
    permissions: write-all
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 18.19.1
          cache: 'pnpm'

      - run: pnpm i
      - uses: nrwl/nx-set-shas@v4

      - name: Run DB Migration
        run: |
          echo "DEFAULT_DB_URL: ${{ secrets.POSTGRES_URL }}" >> .env
          npx nx run storage-postgres:migrate:production

      - name: 'Run Seeds (TODO: remove for production)'
        run: |
          echo "BRANCH_DB_URL: ${{ steps.create-branch.outputs.db_url_with_pooler }}" >> .env
          npx nx run storage-postgres:seed:production

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
